---

- name: enable logstash repository
  apt_repository:
    repo: "deb http://packages.elasticsearch.org/logstash/{{ logstash_version }}/debian stable main"
    state: present

- name: add logstash apt key
  apt_key:
    url: http://packages.elasticsearch.org/GPG-KEY-elasticsearch
    state: present

- name: install logstash package
  apt:
    pkg: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - logstash

- name: create required ssl directory
  file:
    dest: /etc/logstash/ssl
    state: directory
    owner: logstash
    group: ssl-cert

- name: copy SSL certificate
  copy:
    src: "{{ item }}"
    dest: "/etc/logstash/ssl/{{ item | basename }}"
    owner: logstash
    group: ssl-cert
    mode: "0600"
  with_items:
    - files/certs/logstash-forwarder.pem
    - files/certs/logstash-forwarder.key
  notify:
    - restart logstash

- name: create logstash configuration
  template:
    src: "{{ item }}"
    dest: "/etc/logstash/conf.d/{{ item | basename | replace('.j2', '') }}"
    owner: root
    group: root
    mode: "0644"
  with_fileglob:
    - ../templates/conf.d/*
  notify:
    - restart logstash
