---

- name: create grafana directories
  file:
    dest: "{{ item }}"
    state: directory
  with_items:
    - "{{ grafana_root }}"
    - "{{ grafana_root }}/dist"

- name: download grafana
  get_url:
    url: "http://grafanarel.s3.amazonaws.com/grafana-{{ grafana_version }}.tar.gz"
    dest: "{{ grafana_root }}/dist/grafana-{{ grafana_version }}.tar.gz"

- name: extract grafana tarball
  command: >
    tar -zxvf {{ grafana_root}}/dist/grafana-{{ grafana_version }}.tar.gz -C {{ grafana_root}}
  args:
    creates: "{{ grafana_root}}/grafana-{{ grafana_version }}"

- name: link grafana version
  file:
    path: "{{ grafana_root }}/current"
    src: "{{ grafana_root }}/grafana-{{ grafana_version }}"
    state: link 

- name: create config file
  template:
    src: "grafana.js.j2"
    dest: "{{grafana_root}}/grafana-{{grafana_version}}/config.js"
    mode: "u=rw,g=r,o=r"

- name: create apache vhost
  template:
    src: grafana-vhost.j2
    dest: /etc/apache2/sites-available/grafana.conf
    mode: "u=rw,g=r,o=r"
  notify:
    - restart apache

- name: enable apache vhost
  command: >
    a2ensite grafana
  register: a2ensite
  changed_when: '"To activate the new configuration" in a2ensite.stdout'
  notify:
    - restart apache
