---

- name: create temporary directory
  file:
    dest: "{{ github_repo_microservice_temp }}"
    state: directory

- name: clone source repository
  git:
    repo: "git@github.com:{{ github_repo_microservice_organization }}/{{ item.name }}.git"
    dest: "{{ github_repo_microservice_temp }}/{{ item.name }}"
  with_items:
    github_repo_microservice_projects

- name: update gradle.properties
  replace:
    dest: "{{ github_repo_microservice_temp }}/{{ item.name }}/gradle.properties"
    regexp: '^mavenRepoUrl=.*$'
    replace: 'mavenRepoUrl={{ nexus_url }}/content/repositories/releases/'
  with_items:
    github_repo_microservice_projects

- name: update gradle.properties
  replace:
    dest: "{{ github_repo_microservice_temp }}/{{ item.name }}/gradle.properties"
    regexp: '^mavenUser=.*$'
    replace: 'mavenUser=admin'
  with_items:
    github_repo_microservice_projects

- name: update gradle.properties
  replace:
    dest: "{{ github_repo_microservice_temp }}/{{ item.name }}/gradle.properties"
    regexp: '^mavenPassword=.*$'
    replace: 'mavenPassword=admin123'
  with_items:
    github_repo_microservice_projects

- name: update settings.gradle
  replace:
    dest: "{{ github_repo_microservice_temp }}/{{ item.name }}/settings.gradle"
    regexp: '^rootProject.name =.*$'
    replace: 'rootProject.name = "{{ item.name }}"'
  with_items:
    github_repo_microservice_projects

- name: commit changes
  command: >
    git commit -a -m "Update configuration"
    chdir="{{ github_repo_microservice_temp }}/{{ item.name }}"
  ignore_errors: yes
  with_items:
    github_repo_microservice_projects

- name: push code to new repository
  command: >
    git push -u origin master
    chdir="{{ github_repo_microservice_temp }}/{{ item.name }}"
  with_items:
    github_repo_microservice_projects
