---

- name: download archive
  get_url:
    url: "{{ kibana_download_url }}"
    dest: "{{ common_download_dir }}/kibana-{{ kibana_version }}.tar.gz"

- name: create installation directory
  file:
    dest: "{{ kibana_dir }}"
    state: directory

- name: unarchive source
  unarchive:
    src: "{{ common_download_dir }}/kibana-{{ kibana_version }}.tar.gz"
    dest: "{{ kibana_dir }}"
    copy: no

- name: create symlink to current version
  file:
    src: "{{ kibana_dir }}/kibana-{{ kibana_version }}"
    dest: "{{ kibana_dir }}/current"
    state: link

- name: create apache vhost
  template:
    src: kibana-apache-site.j2
    dest: /etc/apache2/sites-available/kibana.conf
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"
  notify:
    -  restart apache

- name: disable default apache site
  command: a2dissite 000-default
  register: a2dissite
  changed_when: '"Site default disabled" in a2dissite.stdout'
  notify:
    -  restart apache

- name: enable site
  command: a2ensite kibana
  register: a2ensite
  changed_when: '"Enabling site" in a2ensite.stdout'
  notify:
    -  restart apache
