---

# logstash configuration
logstash_forwarder_cert: files/certs/logstash-forwarder.pem
logstash_forwarder_key: files/certs/logstash-forwarder.key
logstash_lumberjack_host: kibana.{{ domain }}
logstash_lumberjack_port: 5043

# graphite configuration
graphite_host: graphite.{{ domain }}
grafana_host: grafana.{{ domain }}

# ES configuration
elasticsearch_host: elasticsearch.{{ domain }}

# rundeck configuration
rundeck_host: rundeck.{{ domain }}

# nexus configuration
nexus_url: http://nexus.{{ domain }}:8081/nexus

# seyren configuration
seyren_graphite_url: "http://{{ graphite_host }}"
seyren_port: 8080
seyren_url: "http://{{ graphite_host }}:{{ seyren_port }}"

# kibana
kibana_host: "kibana.{{ domain }}"

# tools location
tools:
  - name: Rundeck
    url: "http://rundeck.{{ domain }}:4440"

  - name: Nexus
    url: "http://nexus.{{ domain }}:8081/nexus/"

  - name: Graphite
    url: "http://graphite.{{ domain }}/"

  - name: Grafana
    url: "http://grafana.{{ domain }}/"

  - name: Kibana
    url: "http://kibana.{{ domain }}/"

  - name: Exhibitor
    url: "http://apps.{{ domain }}:8080/exhibitor/v1/ui/index.html"

  - name: Jenkins
    url: "http://jenkins.{{ domain }}:8080/"

domain: uservices.local

jenkins_seed_job_git_url: https://github.com/uservices-hackathon/jenkins-pipeline-dsl-example.git
jenkins_seed_job_git_branch: sample_pipeline

rundeck_projects:
  - name: "deploy"
    ssh_keypath: "{{ rundeck_basedir }}/.ssh/id_rsa"
    definition:
      - name: Deploy
        loglevel: INFO
        multipleExecutions: true
        sequence:
          keepgoing: false
          strategy: step-first
          commands:
          - scripturl: https://raw.githubusercontent.com/microservice-hackathon/infrastructure/master/scripts/deploy-microservice.sh
        nodefilters:
          dispatch:
            excludePrecedence: true
            keepgoing: false
            rankOrder: ascending
            threadcount: 1
          filter: 'apps name: apps'
        nodesSelectedByDefault: true
        options:
          groupId:
            required: true
          artifactId:
            required: true
          version:
            required: true
          nexusUrl:
            required: true
    resources:
      apps:
        tags: ''
        osFamily: unix
        username: root
        osArch: amd64
        description: App server
        nodename: "apps.{{ domain }}"
        hostname: "apps.{{ domain }}"
        osName: Linux

