---

- name: install required packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - apache2
    - libapache2-mod-wsgi
    - graphite-carbon
    - graphite-web

- name: check if graphite db exists
  stat:
    path: "{{ graphite_db_file }}"
  register: graphite_db_file_stat
  changed_when: false

- name: create graphtie db
  shell: >
    rm -f {{ graphite_db_file }} && /usr/bin/graphite-manage syncdb --noinput
  when: graphite_db_file_stat.stat.exists == false or graphite_db_file_stat.stat.size == 0

- name: set permissions for graphite db
  file:
    dest: "{{ graphite_db_file }}"
    owner: "{{ graphite_user }}"
    group: "{{ graphite_group }}"

- name: create apache vhost
  template:
    src: graphite-vhost.j2
    dest: /etc/apache2/sites-available/graphite-web.conf
    mode: "u=rw,g=r,o=r"
  notify:
    - restart apache2

- name: enable modules
  command: a2enmod wsgi
  register: a2enmod
  changed_when: '"To activate the new configuration" in a2enmod.stdout'
  notify:
    - restart apache2

- name: enable graphite-web site
  command: a2ensite graphite-web
  register: a2ensite
  changed_when: '"To activate the new configuration" in a2ensite.stdout'
  notify:
    - restart apache2
