---

- name: create temporary directory
  file:
    dest: "{{ github_repo_properties_temp }}"
    state: directory

- name: clone source repository
  git:
    repo: "git@github.com:{{ github_repo_properties_organization }}/properties.git"
    dest: "{{ github_repo_properties_temp }}/properties"
    update: no

- name: stage  changes
  command: >
    git add .
    chdir="{{ github_repo_properties_temp }}/properties"
  ignore_errors: yes

- name: commit changes
  command: >
    git commit -a -m "Update configuration"
    chdir="{{ github_repo_properties_temp }}/properties"
  ignore_errors: yes

- name: push code to new repository
  command: >
    git push -u origin master
    chdir="{{ github_repo_properties_temp }}/properties"
